-- Joy Photography: run this in Supabase SQL Editor.
create table if not exists public.photos (
  id bigint generated by default as identity primary key,
  title text not null default '',
  category text not null default 'Other',
  filename text not null,
  caption text not null default '',
  featured boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  format text not null default 'Landscape' check (format in ('Portrait', 'Landscape'))
);

alter table public.photos enable row level security;

-- Public gallery reads. Admin writes happen server-side using the Supabase service-role key.
drop policy if exists "public can read photos" on public.photos;
create policy "public can read photos"
on public.photos for select
to anon, authenticated
using (true);

-- Create a Storage bucket named `photos` in Supabase Dashboard > Storage.
-- Make it PUBLIC so the portfolio can render the image URLs directly.
-- Keep SUPABASE_SERVICE_ROLE_KEY only in Vercel/server environment variables.

-- Persistent admin password settings. The password is stored as a secure hash.
create table if not exists public.admin_settings (
  id bigint primary key check (id = 1),
  password_hash text not null
);
alter table public.admin_settings enable row level security;
-- No public policies: only the server-side service-role key can read/write this table.
